#!/bin/sh

# Extract any of several archive formats.

if [[ -z $1 ]]; then
    echo "\"$1\" is not a valid filename" >&2
    exit 1
elif [ ! -f $1 ]; then
    echo "File \"$1\" does not exist" >&2
    exit 1
else
    case $1 in
        *.7z)        7z x $1       ;;
        *.bz2)       bunzip2 $1    ;;
        *.gz)        gunzip $1     ;;
        *.rar)       unrar x $1    ;;
        *.tar)       tar xvf $1    ;;
        *.tar.bz2)   tar xvjf $1   ;;
        *.tar.gz)    tar xvzf $1   ;;
        *.tar.xz)    tar xf $1     ;;
        *.tbz2)      tar xvjf $1   ;;
        *.tgz)       tar xvzf $1   ;;
        *.zip)       unzip $1      ;;
        *.Z)         uncompress $1 ;;
        *)           echo "File \"$1\" cannot be extracted" >&2
                     exit 1
                     ;;
    esac
fi

exit 0
