#!/bin/bash

# Repeat the given command n times.

if [ $# -le 1 ]; then
    echo "Usage: $0 [number of times to repeat the command] command" >&2
    exit 1
fi
case $1 in
    ''|*[!0-9]*) 
        echo "First argument \"$1\" is not a number" >&2
        exit 1
        ;;
esac

_final=$1
shift
i=0
while [[ $i -lt $_final ]]; do
    eval "$@"
    (( i = i + 1 ))
done

exit 0
