#!/bin/csh -f

if ( $?tcsh ) then
    if ( ${_CHARMAP} == "UTF-8" ) then
        set _SYMBOL_USER = \"`cat ${_SHELLS_DIR}/prompt.user.unicode-s`\"
        set _SYMBOL_ROOT = \"`cat ${_SHELLS_DIR}/prompt.root.unicode-s`\"
    else
        set _SYMBOL_USER = `cat "${_SHELLS_DIR}/prompt.user-s"`
        set _SYMBOL_ROOT = `cat "${_SHELLS_DIR}/prompt.root-s"`
    endif

    set _COLOR_RESET = "%{\033[0m%}"
    set _COLOR_ERR_CODE = ""
    if ( $_TERM_NM_COLORS == 256) then
        set _COLOR_ERR_CODE = "%{\033["`cat ${_SHELLS_DIR}/prompt.errcode.256-s`"m%}"
    else if ( $_TERM_NM_COLORS == 88 ) then
        set _COLOR_ERR_CODE = "%{\033["`cat ${_SHELLS_DIR}/prompt.errcode.88-s`"m%}"
    else if ( $_TERM_NM_COLORS == 8 ) then
        set _COLOR_ERR_CODE = "%{\033["`cat ${_SHELLS_DIR}/prompt.errcode.8-s`"m%}"
    else
        set _COLOR_RESET = ""
    endif

    # FIXME: Use 'alias precmd' or something to set a temporary environment variable containing $status
    # iff $status != 0. The exit code should not be seen when the status equals 0.
    set prompt = "%? %c `if $USER == "root" printf $_SYMBOL_ROOT; endif``if $USER != "root" printf $_SYMBOL_USER; endif` "

    unset _SYMBOL_USER
    unset _SYMBOL_ROOT
    unset _COLOR_RESET
    unset _COLOR_ERR_CODE
else
    set prompt = "> "
endif
